Project setup
Worktez/meet.worktez pull request #1
Opened 2022-07-22 12:49 UTC by Bankar-Swapnil

Project setup

2022-07-23 04:54 UTC, viv9k requested changes
Let's discuss on these changes as I'm not sure if it's good

2022-07-23 04:54 UTC, viv9k commented on src/app/body/body.component.css
> +.hello{
hello?

2022-07-23 05:26 UTC, Bankar-Swapnil commented on src/app/body/body.component.css
> +.hello{
just for  temporary CSS class

2022-08-07 09:33 UTC, viv9k approved these changes
Approved

2022-08-07 09:35 UTC, merged